# Generated by Django 2.0.5 on 2018-05-09 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180505_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedeploy',
            name='previous_deploy_timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
