# Generated by Django 2.0.5 on 2018-05-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_servicedeploy_previous_deploy_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedeploy',
            name='previous_deploy_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
