# Generated by Django 2.0.5 on 2018-05-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20180510_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedeploy',
            name='version',
            field=models.CharField(blank='', default='', max_length=50),
        ),
    ]
